services:
  px4:
    image: px4io/px4-sitl-gazebo:latest
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
      - QT_X11_NO_MITSHM=1
      - PX4_SIM_MODEL=gz_x500_depth
      
      # 1. Name of your world file (minus the .sdf extension)
      - PX4_GZ_WORLD=baylands
      
      # 2. Tell Gazebo to look inside the specific folders we are mounting below
      - GZ_SIM_RESOURCE_PATH=/tmp/custom_gz/worlds:/tmp/custom_gz/models
      
      - PX4_UXRCE_DDS_PORT=8888
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw,Z
      
      # 3. FIX: Mount ONLY your custom simulation folders to an isolated path inside the container
      - ./PX4-Autopilot/Tools/simulation/gz/worlds:/tmp/custom_gz/worlds
      - ./PX4-Autopilot/Tools/simulation/gz/models:/tmp/custom_gz/models
    tty: true
    stdin_open: true

  ros2:
    image: fefon934/ros2-gazebo-px4:latest
    build:
      context: .
      dockerfile: Dockerfile.complete
    network_mode: host
    volumes:
      - ./ros2_ws:/root/ws
    tty: true
    stdin_open: true